name: CI - Build and Test Backend

on:
  push:
    branches:
      - development

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install requirements.txt
        working-directory: ./backend
        run: pip install -r requirements.txt

      - name: Run backend tests
        working-directory: ./backend
        run: pytest || echo "No tests found or failed"

  docker:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: ./backend
        run: |
          docker build -t viniciusyr/emailclassifier-autoudigital-challenge-backend:latest .

      - name: Push Docker image
        run: docker push viniciusyr/emailclassifier-autoudigital-challenge-backend:latest
